<?php

// Plugin definition
$plugin = array(
  'title' => t('Much rows! Such Wow!'),
  'category' => t('Custom layouts'),
  'icon' => 'customlayout2.png',
  'theme' => 'customlayout2',
  'css' => 'customlayout2.css',
  'regions' => array(
    'right_column' => t('Right Column'),
    'first_title' => t('First Title'),
    'first_left' => t('First Left'),
    'first_right' => t('First Right'),
    'second_title' => t('Second Title'),
    'second_left' => t('Second Left'),
    'second_right' => t('Second Right'),
    'third_title' => t('Third Title'),
    'third_left' => t('Third Left'),
    'third_right' => t('Third Right'),
    'fourth_title' => t('Fourth Title'),
    'fourth_left' => t('Fourth Left'),
    'fourth_right' => t('Fourth Right'),
    'fifth_title' => t('Fifth Title'),
    'fifth_left' => t('Fifth Left'),
    'fifth_right' => t('Fifth Right'),
  ),
);
